# Site settings
title: 虫尾山
email: tangoghvan@126.com
description: colortail for fun
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.colortail.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  colortail

# Build settings
markdown: kramdown
